### ISSUE TITLE
非小米手机分享图片到米聊（已安装）无响应

### ISSUE THREAD

**Issue by Chgocn** [MiEcosystem/NewXmPluginSDK#22]
抓取到的相关日志如下：
06-28 10:21:01.611 10857-10857/com.xiaomi.smarthome W/System.err: android.content.pm.PackageManager$NameNotFoundException
        at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:180)
        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:151)
        at com.xiaomi.channel.sdk.MLShareApiFactory.a(MLShareApiFactory.java:96)
        at com.xiaomi.channel.sdk.MLShareApiFactory.<init>(MLShareApiFactory.java:68)
        at com.xiaomi.smarthome.framework.page.CommonShareActivity.g(CommonShareActivity.java:663)
        at com.xiaomi.smarthome.framework.page.CommonShareActivity$3.onClick(CommonShareActivity.java:203)
        at android.view.View.performClick(View.java:6291)
        at android.view.View$PerformClick.run(View.java:24931)
06-28 10:21:01.612 10857-10857/com.xiaomi.smarthome W/System.err:     at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by zhaomingxiaomi** [comment]
请问手机已经安装了米聊是吧？

**Comment by Chgocn** [comment]
是的，在已经安装米聊的情况下。

**Comment by zhaomingxiaomi** [comment]
后面版本会去掉米聊分享
