### ISSUE TITLE
在webview中长按文字调用选中复制功能时崩溃

### ISSUE THREAD

**Issue by hhcc1992** [MiEcosystem/NewXmPluginSDK#47]
2018-10-09 17:30:12.905 5326-5326/com.xiaomi.smarthome:plugin0 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xiaomi.smarthome:plugin0, PID: 5326
    android.content.res.Resources$NotFoundException: Resource ID #0x20e000a
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2155)
        at android.content.res.Resources.getLayout(Resources.java:1155)
        at android.view.MenuInflater.inflate(MenuInflater.java:111)
        at org.chromium.content.browser.selection.SelectionPopupControllerImpl.initializeMenu(SelectionPopupControllerImpl.java:166)
        at org.chromium.content.browser.selection.SelectionPopupControllerImpl.createActionMenu(SelectionPopupControllerImpl.java:172)
        at org.chromium.content.browser.selection.SelectionPopupControllerImpl.onCreateActionMode(SelectionPopupControllerImpl.java:156)
        at org.chromium.android_webview.AwActionModeCallback.onCreateActionMode(AwActionModeCallback.java:13)
        at org.chromium.content.browser.selection.FloatingActionModeCallback.onCreateActionMode(FloatingActionModeCallback.java:6)
        at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onCreateActionMode(DecorView.java:2383)
        at com.android.internal.policy.DecorView.startActionMode(DecorView.java:887)
        at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:843)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:985)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:985)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:985)
        at android.view.View.startActionMode(View.java:6796)
        at org.chromium.content.browser.selection.SelectionPopupControllerImpl.showActionModeOrClearOnFailure(SelectionPopupControllerImpl.java:108)
        at org.chromium.content.browser.selection.SelectionPopupControllerImpl$SmartSelectionCallback.onClassified(SelectionPopupControllerImpl.java:32)
        at org.chromium.content.browser.selection.SmartSelectionProvider$ClassificationTask.onPostExecute(SmartSelectionProvider.java:14)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.access$600(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

搜索这个问题发现，RePlugin项目也有这个问题[https://github.com/Qihoo360/RePlugin/issues/358](https://github.com/Qihoo360/RePlugin/issues/358)，也许可以参考下

**Comment by wongzy** [comment]
请问具体是在哪个界面的webview出现的问题，必现吗？

**Comment by wongzy** [comment]
> @wongzy 必现的，自己的插件里面，写的webview会出现。使用小米 mix测试出来的 android8.0

您好，我们提供了加载WebView的接口，您可以了解下是否符合您的需求，可参考本项目中plugProject中的PluginDemo，com.xiaomi.xmplugindemo类中的52行
```Java
mHostActivity.loadWebView("http://home.mi.com", "MiHome");
```
还有问题可继续反馈，谢谢。
