### ISSUE TITLE
通知栏问题

### ISSUE THREAD

**Issue by Tywei24** [MiEcosystem/NewXmPluginSDK#54]
应用在后台，收到通知栏的消息后，点击进入到应用主界面。报错java.lang.NullPointerException:Attempt to  read from field 'java.lang.String com.xiaomi.smarthome.device.api.DeviceStat.did' on a null object reference at com.miaomiaoce.thermo.Device.getDevice(Device.java:34) at com.miaomiaoce.thermo.MainActivity.onCreate(MainActivity.java:178) at com.xiaomi.smarthome.frame.plugin.runtime.activity.PluginhostActivity.launchActivity(PluginhostActivity.java:178).....

**Comment by Tywei24** [comment]
已解决！
